services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust  
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  

  web:
    image: odoo:19.0
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
    environment:
      HOST: db
      USER: odoo
      PASSWORD:

volumes:
  odoo-db-data: